year_3/Semester-6/Metrici software/ELearningPlatform/ELearningPlatform/Controllers/Admin Dashboard/UsersManagementController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using AutoMapper;
using ELearningPlatform.DataLayer.Edmx;
using ELearningPlatform.DataLayer.Repository;
using ELearningPlatform.Models;
using ELearningPlatform.Models.ViewModels;
using Microsoft.AspNet.Identity;
using ELearningPlatform.Controllers.Shared;
using Microsoft.AspNet.Identity.EntityFramework;
using System.IO;

namespace ELearningPlatform.Controllers.Admin_Dashboard
{
    public class UsersManagementController : BaseController
    {
        private readonly UniversityStaffRepository _universityStaffRepository = new UniversityStaffRepository();
        private const string ERRORTAG = "ErrorMessage";
        public ActionResult UsersIndex()
        {
            return View("UsersIndex");
        }

        public ActionResult UserCreate()
        {
            UserViewModel model = new UserViewModel();
            model.RolesList = GetRolesAsSelectListItem();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> UserCreate(UserViewModel model)
        {
            if (string.IsNullOrEmpty(model.Password))
            {
                ModelState.AddModelError(ERRORTAG, "Password is required.");
            }
            if (ModelState.IsValid)
            {

                var user = new ApplicationUser
                {
                    UserName = model.Email,
                    Email = model.Email,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    DateCreated = DateTime.UtcNow.ToString(CultureInfo.InvariantCulture),
                    IsSuspended = model.IsSuspended
                };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    var role = GetRole(model.Role);
                    await UserManager.AddToRoleAsync(user.Id, role);
                    if (role == UserRolesEnum.Teacher.ToString())
                    {
                        _universityStaffRepository.Add(new UniversityStaff() { Id = user.Id });
                    }
                    return RedirectToAction("UsersIndex");
                }
            }
            ViewBag.ModelState = ModelState;
            model.RolesList = GetRolesAsSelectListItem();
            return View("UserCreate", model);
        }

        public ActionResult UserEdit(string id)
        {
            ApplicationUser aspNetUser = UserManager.FindById(id);
            UserViewModel userViewModel = Mapper.Map<UserViewModel>(aspNetUser);
            userViewModel.RolesList = GetRolesAsSelectListItem();
            return View("UserEdit", userViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> UserEdit(string id, UserViewModel model)
        {
            //if (ModelState.IsValid)
            //{
            //    ApplicationUser applicationUser = Mapper.Map<ApplicationUser>(model);
            //    IList<string> role = UserManager.GetRoles(applicationUser.Id);
            //    foreach (string r in role)
            //    {
            //        UserManager.RemoveFromRole(applicationUser.Id, r);
            //    }
            //    await UserManager.AddToRoleAsync(applicationUser.Id, model.Role);
            //    await UserManager.UpdateAsync(applicationUser);
            //    ViewBag.Succes = true;
            //    model.RolesList = GetRolesAsSelectListItem();
            //    return View("UserEdit", model);
            //}
            //ViewBag.ModelState = ModelState;
            //model.RolesList = GetRolesAsSelectListItem();
            //return View("UserEdit", model);

            UserManager<ApplicationUser> userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            if (string.IsNullOrEmpty(model.Password))
            {
                ModelState.Remove("Password");
            }
            if (ModelState.IsValid)
            {
                ApplicationUser applicationUser = await UserManager.FindByIdAsync(model.Id);
                applicationUser.FirstName = model.FirstName;
                applicationUser.LastName = model.LastName;
                applicationUser.IsSuspended = model.IsSuspended;
                applicationUser.Email = model.Email;

                IList<string> rolesList = UserManager.GetRoles(applicationUser.Id);
                foreach (string r in rolesList)
                {
                    UserManager.RemoveFromRole(applicationUser.Id, r);
                }
                var role = GetRole(model.Role);
                await UserManager.AddToRoleAsync(applicationUser.Id, role);
                ViewBag.Succes = true;
                model.RolesList = GetRolesAsSelectListItem();
                return View("UserEdit", model);
            }
            ViewBag.ModelState = ModelState;
            model.RolesList = GetRolesAsSelectListItem();
            return View("UserEdit", model);
        }

        public ActionResult Delete(string id)
        {
            ApplicationUser applicationUser = UserManager.FindById(id);
            UserManager.Delete(applicationUser);
            return RedirectToAction("UsersIndex");
        }

        public ActionResult StudentCreate()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> StudentCreate(StudentViewModel model)
        {
            StudentsRepository studentsRepository = new StudentsRepository();
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser
                {
                    UserName = model.Email,
                    Email = model.Email,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    DateCreated = DateTime.UtcNow.ToString(CultureInfo.InvariantCulture),
                    IsSuspended = model.IsSuspended
                };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await UserManager.AddToRoleAsync(user.Id, UserRolesEnum.Student.ToString());
                    Students student = new Students()
                    {
                        Id = user.Id,
                        UniqueNumber = model.UniqueNumber
                    };
                    studentsRepository.Add(student);
                    return RedirectToAction("UsersIndex");
                }
            }
            return View("StudentCreate", model);
        }

        public string GetRoleById(string roleId)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            return db.Roles.Where(x => x.Id == roleId).Select(r => r.Name).FirstOrDefault();
        }

        [HttpGet]
        public JsonResult GetUsers(DataTableRequest request)
        {
            DataTableResponse response = new DataTableResponse()
            {
                aaData = new List<List<string>>()
            };
            List<ApplicationUser> users = UserManager.Users.ToList();
            foreach (ApplicationUser user in users)
            {
                string userRoleId = user.Roles.First().RoleId;
                string roleName = GetRoleById(userRoleId);
                response.aaData.Add(new List<string>()
                {
                    string.Format("{0} {1}",user.FirstName , user.LastName),
                    user.UserName,
                    roleName,
                    user.IsSuspended ? "Suspended" : "Active" ,
                    Convert.ToDateTime(user.DateCreated).ToShortDateString(),
                    user.Id
                });
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }


        private string GetRole(string id)
        {
            ApplicationDbContext db = new ApplicationDbContext();
            return db.Roles.Where(x => x.Id == id).Select(r => r.Name).FirstOrDefault();
        }
        private List<string> GetRoles()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            return db.Roles.Where(x => x.Name != "Student").Select(r => r.Name).ToList();
        }
        private List<SelectListItem> GetRolesAsSelectListItem()
        {
            ApplicationDbContext db = new ApplicationDbContext();
            return db.Roles.Where(x => x.Name != "Student").Select(r => new SelectListItem()
            {
                Text = r.Name,
                Value = r.Id
            }).ToList();
        }

        public async Task<ActionResult> StudentsCreate()
        {
            UserViewModel model;
            var filepath = @"C:\Users\Cipri\Desktop\randomNames.txt";
            string[] lines = System.IO.File.ReadAllLines(filepath);
            StudentsRepository studentsRepository = new StudentsRepository();
            foreach (var item in lines)
            {
                Random random = new Random(Guid.NewGuid().GetHashCode());

                model = new UserViewModel()
                {
                    Email = string.Format("{0}.{1}@ubbcluj.ro", item.Split(' ')[0].ToLower(), item.Split(' ')[1].ToLower()),
                    FirstName = item.Split(' ')[0],
                    LastName = item.Split(' ')[1],
                    IsSuspended = false,
                    Password = "google",
                    Role = "feb3444a-e995-401e-8996-a64734c4e24a"
                };
                var user = new ApplicationUser
                {
                    UserName = model.Email,
                    Email = model.Email,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    DateCreated = DateTime.UtcNow.ToString(CultureInfo.InvariantCulture),

year_3/Semester-6/Metrici software/ELearningPlatform/ELearningPlatform/Views/UsersManagement/StudentCreate.cshtml
@model ELearningPlatform.Models.ViewModels.StudentViewModel

@using (Html.BeginForm("StudentCreate", "UsersManagement", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.Partial("_ErrorHandling")
    <div class="form-horizontal">
        <div class="panel panel-default">
            <div class="panel-heading">
                Student Data
            </div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ConfirmPassword, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsSuspended, new { @class = "control-label col-md-2" })
                    <div class="checkbox col-md-8">
                        @Html.EditorFor(model => model.IsSuspended)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.UniqueNumber, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UniqueNumber, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <div class="col-md-offset-2 col-nd-12">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

year_3/Semester-6/Metrici software/ELearningPlatform/ELearningPlatform/Views/UsersManagement/UserCreate.cshtml
@using ELearningPlatform.Models.ViewModels;
@model UserViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Partial("_ErrorHandling")
    <div class="form-horizontal">
        <div class="panel panel-default">
            <div class="panel-heading">
                User Data
            </div>
            <div class="panel-body">
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ConfirmPassword, new {@class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ConfirmPassword, new {htmlAttributes = new {@class = "form-control"}})
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IsSuspended, new { @class = "control-label col-md-2" })
                    <div class="checkbox col-md-8">
                        @Html.EditorFor(model => model.IsSuspended)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Role, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Role", Model.RolesList, new { @class = "form-control" })
                    </div>
                </div>

            </div>
            <div class="panel-footer">
                <div class="col-md-offset-2 col-nd-12">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

year_3/Semester-6/Metrici software/ELearningPlatform/ELearningPlatform/Views/UsersManagement/UserDelete.cshtml
@using ELearningPlatform.Models.ViewModels;
@model UserViewModel

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConfirmPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConfirmPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "UsersManagement",FormMethod.Post)) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "UsersIndex")
        </div>
    }
</div>

year_3/Semester-6/Metrici software/ELearningPlatform/ELearningPlatform/Views/UsersManagement/UserEdit.cshtml
@model ELearningPlatform.Models.ViewModels.UserViewModel

@using (Html.BeginForm("UserEdit", "UsersManagement", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.Partial("_ErrorHandling")
    @Html.HiddenFor(m => m.Id)
    <div class="form-horizontal">
        <div class="panel panel-default">
            <div class="panel-heading">
                User Data
            </div>
            <div class="panel-body">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="form-group">
                    @Html.LabelFor(model => model.IsSuspended, new { @class = "control-label col-md-2" })
                    <div class="checkbox col-md-8">
                        @Html.EditorFor(model => model.IsSuspended)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Role, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("Role", Model.RolesList, new { @class = "form-control" })
                    </div>
                </div>

            </div>
            <div class="panel-footer">
                <div class="col-md-offset-2 col-nd-12">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}

year_3/Semester-6/Metrici software/ELearningPlatform/ELearningPlatform/Views/UsersManagement/UsersIndex.cshtml
@Scripts.Render("~/UsersManagementScripts")
@Styles.Render("~/UsersManagementStyles")


<a href="@Url.Action("UserCreate")">
    <div class="btn btn-default createNew">
        Create New User
    </div>
</a>

<a href="@Url.Action("StudentCreate")">
    <div class="btn btn-default createNew">
        Create New Student
    </div>
</a>
<table id="usersTable" class="table table-striped table-bordered dataTable no-footer" width="100%">
    <thead>
    <tr>
        <th>Fullname</th>
        <th>UserName</th>
        <th>Role</th>
        <th>Suspended</th>
        <th>Date Created</th>
        <th>Actions</th>
    </tr>
    </thead>
</table>

<script>
    jQuery(document).ready(function () {
        new ELearningPlatform.UsersManagement();
    });
</script>